version: '3.8'

services:
  web:
    build: .
    ports:
      - "8002:8002"
    depends_on:
      - db
      - rabbitmq
    environment:
      - DATABASE_URL=postgresql://postgres:root@db/commandes
      - RABBITMQ_URL=amqp://guest:guest@rabbitmq/
    networks:
      - shared-network

  db:
    image: postgres:13
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: root
      POSTGRES_DB: commandes
    ports:
      - "5436:5434"
    networks:
      - shared-network

  rabbitmq:
    image: rabbitmq:3-management
    ports:
      - "5674:5672"
      - "15674:15674"
    networks:
      - shared-network

networks:
  shared-network:
    external: true
