"""Initial migration

Revision ID: 486655eb1574
Revises: 888bf010f178
Create Date: 2024-06-07 10:05:29.828029

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '486655eb1574'
down_revision: Union[str, None] = '888bf010f178'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('commandes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('clientId', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_commandes_clientId'), 'commandes', ['clientId'], unique=False)
    op.create_index(op.f('ix_commandes_id'), 'commandes', ['id'], unique=False)
    op.create_table('commande_produits',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('commande_id', sa.Integer(), nullable=True),
    sa.Column('produitId', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['commande_id'], ['commandes.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_commande_produits_id'), 'commande_produits', ['id'], unique=False)
    op.create_index(op.f('ix_commande_produits_produitId'), 'commande_produits', ['produitId'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_commande_produits_produitId'), table_name='commande_produits')
    op.drop_index(op.f('ix_commande_produits_id'), table_name='commande_produits')
    op.drop_table('commande_produits')
    op.drop_index(op.f('ix_commandes_id'), table_name='commandes')
    op.drop_index(op.f('ix_commandes_clientId'), table_name='commandes')
    op.drop_table('commandes')
    # ### end Alembic commands ###
